# Generated by Django 5.0.4 on 2024-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=256, unique=True)),
                ("Description", models.TextField()),
                ("Start_date", models.DateTimeField(auto_now=True)),
                ("End_date", models.DateTimeField()),
                (
                    "Status",
                    models.CharField(
                        choices=[("A", "Active"), ("F", "Finished"), ("C", "Canceled")],
                        default="A",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
