# Generated by Django 5.0.4 on 2024-04-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=256)),
                ("Description", models.TextField()),
                ("Creation_date", models.DateTimeField(auto_now=True)),
                ("Deadline_date", models.DateTimeField(null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("U", "Underway"),
                            ("D", "Done"),
                            ("C", "Canceled"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project",
                        to="projects.projects",
                    ),
                ),
            ],
        ),
    ]
